# Detect and label pull requests that have merge conflicts
name: 🏗️ Check Merge Conflicts
on:
  push:
    branches:
    - master
jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: mschilde/auto-label-merge-conflicts@591722e97f3c4142df3eca156ed0dcf2bcd362bd # master
        with:
          CONFLICT_LABEL_NAME: "🚫 Merge Conflicts"
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
