# Inserts list of contributors and community members into ./docs/credits.md
# Also generates an SVG showing all contributors, which is embedded into readme
name: 📊 Generate Contributor Credits
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  # Job #1 - Generate an embedded SVG asset, showing all contributors
  generate-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: bubkoo/contributors-list@b9e91f91a51a55460fdcae64daad0cb8122cdd53 # v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          svgPath: docs/assets/CONTRIBUTORS.svg
          affiliation: all
          includeBots: false
          excludeUsers: BeginCI snyk-bot
          avatarSize: 96
          userNameHeight: 20
          svgWidth: 830
          commitMessage: ':blue_heart: Updates contributor SVG'
  # Job #2 - Fetches sponsors and inserts into readme and credits page
  insert-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout 🛎️
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Generate Sponsors in Readme 💖
        uses: JamesIves/github-sponsors-readme-action@df44e2a5686dc94a4ee26bee756da7a73ccf3a0c # 1.0.5
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          file: 'README.md'
      - name: Generate Sponsors in Credits 💖
        uses: JamesIves/github-sponsors-readme-action@df44e2a5686dc94a4ee26bee756da7a73ccf3a0c # 1.0.5
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          file: 'docs/credits.md'
  # Job #3 - Update the Credits page
  insert-credits:
    runs-on: ubuntu-latest
    name: Inserts contributors into credits.md
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: Contributer List - Credits Page
      uses: akhilmhdh/contributors-readme-action@098389139f2fabed92e52606268941dbff381edb # v2.3.6
      env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      with:
        image_size: 80
        readme_path: docs/credits.md
        columns_per_row: 6
        commit_message: ':purple_heart: Updates contributors list'
        collaborators: all
        committer_username: liss-bot
        committer_email: liss-bot@d0h.co
    - name: Sponsors List - Readme
      uses: akhilmhdh/contributors-readme-action@697368357571d95fdf3d88edc0daac86ca4ee8a5 # v2.2
      env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      with:
        image_size: 80
        readme_path: README.md
        columns_per_row: 6
        commit_message: ':yellow_heart: Updates sponsors table'
        committer_username: liss-bot
        committer_email: liss-bot@d0h.co

