# When a new comment is added to an issue, if it had the Stale or Awaiting User Response labels,
# then those labels will be removed, providing it was not user lissy93 who added the commend. 
name: 🎯 Remove Pending Labels on Close
on:
  issues:
    types: [closed]
permissions:
  contents: read

jobs:
  remove-labels:
   runs-on: ubuntu-latest
   steps:
   - name: Harden Runner
     uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
     with:
       egress-policy: audit

   - name: Remove Labels when Closed
     uses: actions-cool/issues-helper@a4367f11ada25af22aa188cb0bc81143b3569193 # v2.5.0
     with:
      actions: remove-labels
      token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      issue-number: ${{ github.event.issue.number }}
      labels: '🚏 Awaiting User Response,⚰️ Stale,👤 Awaiting Maintainer Response'
