# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0' # At 03:30 on Sunday
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1.1.1
        with:
          target_repo_url: git@codeberg.org:alicia/dashy.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
